language: csharp
mono: none
dotnet: 3.1.100

os:
  - linux
  - osx

dist: bionic
osx_image: xcode11.2

script:
  - dotnet restore src/stashbox.mocking.sln
  - dotnet test src/stashbox.mocking.fakeiteasy.tests/stashbox.mocking.fakeiteasy.tests.csproj -c Release -f netcoreapp3.1
  - dotnet test src/stashbox.mocking.moq.tests/stashbox.mocking.moq.tests.csproj -c Release -f netcoreapp3.1
  - dotnet test src/stashbox.mocking.nsubstitute.tests/stashbox.mocking.nsubstitute.tests.csproj -c Release -f netcoreapp3.1