environment:
  build_version: 2.3.3

version: $(build_version)-{build}

pull_requests:
  do_not_increment_build_number: true
  
configuration: Release

image: Visual Studio 2019

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(build_version)
  assembly_file_version: $(build_version)
  assembly_informational_version: $(build_version)

before_build:
- ps: . .\patch-version.ps1 src\stashbox.mocking.fakeiteasy\stashbox.mocking.fakeiteasy.csproj $($env:build_version)
- ps: . .\patch-version.ps1 src\stashbox.mocking.moq\stashbox.mocking.moq.csproj $($env:build_version)
- ps: . .\patch-version.ps1 src\stashbox.mocking.nsubstitute\stashbox.mocking.nsubstitute.csproj $($env:build_version)

build_script:
- nuget restore src\stashbox.mocking.sln
- msbuild /t:Restore /p:Configuration=%CONFIGURATION% src\stashbox.mocking.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% src\stashbox.mocking.sln
  
after_build:
- msbuild /t:Pack /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox.mocking.fakeiteasy\stashbox.mocking.fakeiteasy.csproj
- msbuild /t:Pack /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox.mocking.moq\stashbox.mocking.moq.csproj
- msbuild /t:Pack /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\..\artifacts src\stashbox.mocking.nsubstitute\stashbox.mocking.nsubstitute.csproj
- nuget pack src\stashbox.mocking.rhino.mocks\stashbox.mocking.rhino.mocks.csproj -Symbols -SymbolPackageFormat snupkg -OutputDirectory %APPVEYOR_BUILD_FOLDER%\artifacts

test_script:
- dotnet test src\stashbox.mocking.fakeiteasy.tests\stashbox.mocking.fakeiteasy.tests.csproj -c %CONFIGURATION% -f net452 --no-build
- dotnet test src\stashbox.mocking.fakeiteasy.tests\stashbox.mocking.fakeiteasy.tests.csproj -c %CONFIGURATION% -f netcoreapp1.1 --no-build
- dotnet test src\stashbox.mocking.fakeiteasy.tests\stashbox.mocking.fakeiteasy.tests.csproj -c %CONFIGURATION% -f netcoreapp2.0 --no-build
- dotnet test src\stashbox.mocking.moq.tests\stashbox.mocking.moq.tests.csproj -c %CONFIGURATION% -f net452 --no-build
- dotnet test src\stashbox.mocking.moq.tests\stashbox.mocking.moq.tests.csproj -c %CONFIGURATION% -f netcoreapp1.1 --no-build
- dotnet test src\stashbox.mocking.moq.tests\stashbox.mocking.moq.tests.csproj -c %CONFIGURATION% -f netcoreapp2.0 --no-build
- dotnet test src\stashbox.mocking.nsubstitute.tests\stashbox.mocking.nsubstitute.tests.csproj -c %CONFIGURATION% -f net452 --no-build
- dotnet test src\stashbox.mocking.nsubstitute.tests\stashbox.mocking.nsubstitute.tests.csproj -c %CONFIGURATION% -f netcoreapp1.1 --no-build
  
artifacts:
  - path: artifacts\Stashbox.*.nupkg
    name: NuGet Packages
  - path: artifacts\Stashbox.*.snupkg
    name: NuGet Symbol Packages

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true